#!/bin/sh
set -e -u

# Ensure this pre-commit hook is installed
(cd .git/hooks && ln -sf "../../${0##*/}" pre-commit)

# Bash has been GPLv3 since version 4, so macOS still ships version 3.
# Do some minimal validation that we can bootstrap a newer version.
[ -x /bin/bash ] && BASH_COMPAT=3.2 /bin/bash -n mac.sh
