# ~/.gemini/antigravity-cli/settings.json
#
# https://antigravity.google/docs/cli/settings

allowNonWorkspaceAccess: true
colorScheme: dark
enableBusinessLogin: false
enableTelemetry: false
enforceHttpsUrls: true
notifications: true
remoteControlEnabled: true
showFeedbackSurvey: false
verbosity: low

# https://antigravity.google/docs/cli/statusline
statusLine:
  command: ~/.gemini/antigravity-cli/bin/statusline.jq
  type: command

# https://antigravity.google/docs/cli/title
title: {}

# Permissions are in `~/.gemini/config/config.json` to be shared with the GUI.
enableTerminalSandbox: true
