# ~/.gemini/antigravity-cli/settings.json
#
# https://antigravity.google/docs/cli/settings

allowNonWorkspaceAccess: true
colorScheme: dark
enableTelemetry: false
enforceHttpsUrls: true
notifications: true
showFeedbackSurvey: false
verbosity: low

# https://antigravity.google/docs/cli/statusline
statusLine:
  enabled: true

# https://antigravity.google/docs/cli/title
title: {}

# Permissions are in `~/.gemini/config/config.json` to be shared with the GUI.
enableTerminalSandbox: true
