#!/bin/bash
# shellcheck source=/dev/null
#
# ~/.bashrc: executed by interactive bash.

if [ "$SHELL" != "$HOME/.local/bin/bash" ] && [ -x "$HOME/.local/bin/bash" ]; then
	export SHELL="$HOME/.local/bin/bash"
	exec "$SHELL"
fi

HISTCONTROL=ignoredups:ignorespace
HISTFILE="$HOME/.history"
HISTSIZE=1000
PS1='\[\e[01;$([ $? != 0 ] && printf 31 || printf 32)m\]●\[\e[00m\] ' # circle colored per exit code
PS1="$PS1"'\[\e[01;34m\]\W\[\e[00m\] ' # current directory basename

shopt -s checkwinsize # update COLUMNS and LINES after every command.
shopt -s globstar     # match directories and subdirectories with **.
shopt -s histappend   # append to HISTFILE rather than overwrite it.

if [[ "$OSTYPE" == darwin* ]]; then
	export CLICOLOR=1
else
	alias ls='ls --color=auto'
fi

{ [ -x "$(command -v dircolors)" ] && eval "$(dircolors --bourne-shell)"; } || true
{ [ -f "$HOME/.config/interactive" ] && . "$HOME/.config/interactive"; } || true
