#!/bin/sh
# shellcheck source=/dev/null

export EDITOR='nvim'
export LANG='en_US.UTF-8'
export LESS='-R'
export PATH="${HOME}/.local/go/bin:${PATH}"
export PATH="${HOME}/.local/node/bin:${PATH}"
export PATH="${HOME}/.local/homebrew/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.pyenv/shims:${HOME}/.pyenv/bin:${PATH}"
export PATH="${HOME}/go/bin:${PATH}"
export PYTHONUSERBASE="${HOME}/.local"

if [ -z "$(command -v pbcopy ||:)" ]
then
	if [ -n "${WAYLAND_DISPLAY}" ] && [ -n "$(command -v wl-copy ||:)" ]
	then alias pbcopy='wl-copy --type text/plain'

	elif [ -n "${TMUX}" ] && [ -n "$(command -v tmux ||:)" ]
	then alias pbcopy='tmux load-buffer -w -'

	else
		# As a last resort, send stdin to the terminal using OSC 52:
		# https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
		alias pbcopy='base64 -w0 | xargs -0 printf "\e]52;c;%s\e\\"'
	fi
fi

if [ -z "$(command -v pbpaste ||:)" ]
then
	if [ -n "${WAYLAND_DISPLAY}" ] && [ -n "$(command -v wl-paste ||:)" ]
	then alias pbpaste='wl-paste --no-newline'
	fi
fi

# The Crostini terminal supports truecolor but does not export COLORTERM.
# https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/js/hterm_preference_manager.js
if [ -n "$(pgrep -f 'google/cros-containers' ||:)" ]
then export COLORTERM='truecolor'
fi

alias ag='rg --smart-case'
alias ybat='bat --language yaml'

for f in chruby/chruby.sh chruby/auto.sh
do [ -r "${HOME}/.local/share/${f}" ] && . "${HOME}/.local/share/${f}"
done
