#!/bin/sh
# shellcheck source=/dev/null

export EDITOR='nvim'
export LANG='en_US.UTF-8'
export LESS='-R'

# Local fameworks are usually newer than those installed by package managers; search them first.
# NOTE: "$*" expands arguments to a single word separated by IFS.
PATH=$(IFS=: && set -- \
"${HOME}/.cargo/bin" \
"${HOME}/.local/go/bin:${HOME}/go/bin" \
"${HOME}/.local/node/bin" \
"${HOME}/.pyenv/shims:${HOME}/.pyenv/bin" \
"${HOME}/.local/bin:${HOME}/.local/homebrew/bin" \
"${PATH}" && echo "$*")

export KUBECOLOR_CONFIG="${HOME}/.config/kubecolor.yaml"
export PYTHONUSERBASE="${HOME}/.local"

if [ -z "$(command -v pbcopy ||:)" ]
then
	if [ -n "${WAYLAND_DISPLAY}" ] && [ -n "$(command -v wl-copy ||:)" ]
	then alias pbcopy='wl-copy --type text/plain'

	elif [ -n "${TMUX}" ] && [ -n "$(command -v tmux ||:)" ]
	then alias pbcopy='tmux load-buffer -w -'

	else
		# As a last resort, send stdin to the terminal using OSC 52:
		# https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
		alias pbcopy='base64 -w0 | xargs -0 printf "\e]52;c;%s\e\\"'
	fi
fi

if [ -z "$(command -v pbpaste ||:)" ]
then
	if [ -n "${WAYLAND_DISPLAY}" ] && [ -n "$(command -v wl-paste ||:)" ]
	then alias pbpaste='wl-paste --no-newline'
	fi
fi

# The Crostini terminal supports truecolor but does not export COLORTERM.
# https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/js/hterm_preference_manager.js
if [ -n "$(pgrep -f 'google/cros-containers' ||:)" ]
then export COLORTERM='truecolor'
fi

alias ag='rg --smart-case'
alias ka='kubectl apply --server-side'
alias ybat='bat --language yaml'

for f in chruby/chruby.sh chruby/auto.sh
do [ -r "${HOME}/.local/share/${f}" ] && . "${HOME}/.local/share/${f}"
done
