#!/dev/null/bash
# https://direnv.net
#
# ~/.config/direnv/direnvrc: Bash code loaded before every .envrc.

# add PostgreSQL client tools to PATH by looking for `pg_config`.
use_postgresql() {
	local version="${1-}"
	version="${version%%.*}"

	local match
	match=$(pg_config --version 2> /dev/null)

	# return early when tools on PATH are an acceptable version.
	[[ -n "${version}" && "${match}" =~ " ${version}"($|[^0-9]) ]] && return
	[[ -z "${version}" && -n "${match}" ]] && return

	# use `command` to search for `pg_config` in versioned paths.
	[[ -n "${version}" ]] && match=$(
		PATH=$(IFS=: && set -- \
			"${HOME}/.local/homebrew/opt/postgresql@${version}/bin" \
			"/usr/lib/postgresql/${version}/bin" \
			"/usr/libexec/postgresql${version}" \
			"/usr/pgsql-${version}/bin" \
			&& echo "$*")
		command -v pg_config
	)

	# use nullglob to select a `pg_config` with the largest versioned path.
	[[ -z "${version}" ]] && match=$(shopt -s nullglob \
		&& printf '%s\n' \
		"${HOME}/.local/homebrew/opt/postgresql@"*/bin/pg_config \
		/usr/lib/postgresql/*/bin/pg_config \
		/usr/libexec/postgresql*/pg_config \
		/usr/pgsql-*/bin/pg_config \
		| sort -rnt/
	)

	local error
	: "${match:-${error:?PostgreSQL ${version:+${version} }not installed}}"

	# add the first/largest directory to PATH.
	match="${match%%$'\n'*}" && PATH_add "${match%/*}"
}

# https://direnv.net/docs/ruby.html
use_ruby() {
	local method
	if [[ -n "${1-}" ]]
	then method="${1?}"
	elif [[ -r '.ruby-version' ]]
	then method='.ruby-version'
	elif [[ -r 'Gemfile' ]]
	then method='Gemfile'
		# Use a recent Ruby when Bundler is missing or too old to read this Gemfile.
		bundle platform --ruby &> /dev/null || use_ruby 'any' || return
	fi

	local version
	case "${method}" in
		'.ruby-version') read -r version < '.ruby-version' || return ;;
		'Gemfile') read -r _ version <<< "$(bundle platform --ruby ||:)" || return ;;
		'any') ;;
		*) version="${method}"
	esac

	# search for an exact match or longest partial match.
	# glob results are sorted, and longer numbers are often larger.
	# NOTE: this not a thorough version comparison.
	#
	# https://github.com/postmodern/ruby-install
	local dir match
	for dir in "${RUBY_INSTALL_RUBIES_DIR:-${HOME}/.rubies}"/*; do
		case "${dir##*/}" in
			"${version}") match="${dir}" && break ;;
			*"${version}"*) [[ "${#dir}" -ge "${#match}" ]] && match="${dir}" ;;
			*)
		esac
	done

	local error
	load_prefix "${match:-${error:?Ruby ${version:+${version} }not installed}}"

	# NOTE: layout_ruby included with direnv caches gems per project.

	# isolate gems by Ruby engine and version.
	# https://guides.rubygems.org/command-reference
	GEM_HOME="${HOME?}/.gem/${match##*/}"
	export GEM_HOME
	PATH_add "${GEM_HOME}/bin"

	# install gems to $GEM_HOME and symlink executables locally.
	# https://bundler.io/man/bundle-config.1.html
	BUNDLE_BIN="$(direnv_layout_dir)/bin"
	export BUNDLE_BIN
	export BUNDLE_PATH__SYSTEM=true
	PATH_add "${BUNDLE_BIN}"
}
